#+OPTIONS: ^:nil

前些天，我的电脑总是时不时的断网，每次我得重启dhcpcd服务。 我的系统是
Arch Linux，网络用的是dhcpcd＋wpa_supplicant。首先确定的是网络本身没有
问题。 dmesg看了一眼，发现这样的信息" ath10k_pci 0000:3a:00.0:
firmware crashed!"。网上搜了一下，了 解到aht10k是一个无线网卡驱动，专
为Qualcom Atheros QCA988x（高通）系列， 详情见这里
[[https://wireless.wiki.kernel.org/en/users/drivers/ath10k]]。

#+BEGIN_QUOTE
$ lspci
......
3a:00.0 Network controller: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter (rev 32)
3b:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS525A PCI Express Card Reader (rev 01)
3c:00.0 Non-Volatile memory controller: Toshiba America Info Systems XG4 NVMe SSD Controller (rev 01)
#+END_QUOTE

可以看到我的网卡正是Qualcom Atheros，由此可以确定断网问题和ath10k有关。

升级firemare可能能解决问题，升级方法也很简单，只要直接替换对应的firmware镜像
文件就可以了。它在 [[https://github.com/kvalo/ath10k-firmware][ath10-firmware.git]] 中开发，最终合并到 [[https://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git/][linux-firmware.git]] 中，我系
统现在使用的版本是20180119.2a713be-1，这已经是Arch的最新版了。我需要从
它的git库中下载最新的。但是这个库看起来非常大，包含了各种设备的
firmware，而我只需要其中的一个。还好 [[https://git.kernel.org ]] 提供了一种
plan模式，你可以直接用HTTP下载单个文件。打开我设备型号对应的目录：

#+BEGIN_QUOTE
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/ath10k/QCA6174/hw3.0/
/ath10k/QCA6174/hw3.0/
../
board-2.bin
board.bin
firmware-4.bin
firmware-6.bin
notice_ath10k_firmware-4.txt
notice_ath10k_firmware-6.txt
#+END_QUOTE

还不只一个文件，那就整个目录替换吧。一个一个下又点麻烦，用wget。

#+BEGIN_QUOTE
wget -c -e robots=off -r -l1 --debug https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/ath10k/QCA6174/hw3.0/
#+END_QUOTE

开始时一值只能下到一个index.html，看了一边手册，确信-r是递归下载，也没
找到其他又用的选项。打开debug模式，原来是wget遵循了robots规则，而
[[https://git.kernel.org]] 禁止一切爬虫。然后我在wget的info找到了关闭它的
方法 ~robots=off~ 。而这时我的网络已经快崩溃了，重启一次dhcpcd只能维持不到
半分钟，还好wget被设计成在慢速或不可靠网络下也保持健壮性，失败的时候会重
连。这样在这种艰苦的条件下，这几个文件终于被下载下来了。

接着就是备份原来的目录，复制新的firmware文件。reboot。一切恢复正常。

firmware crashed 的原因应该是我最近一次系统升级导致的，内核升级到
4.15.10,ath10k驱动和firmware不兼容导致的。
